
# use NGINX default configuration
events {}

http {
    server {
        listen 80;
        # default server name
        server_name _;

        # frontend request
        location / {
            # nginx -> Vite
            proxy_pass http://frontend:5173; 
            proxy_set_header Host localhost;
            # give the real IP address of the client to the backend (but not IP of NGINX)
            # x: self-defined header
            proxy_set_header X-Real-IP $remote_addr;
            # remember all the IP addresses (client, NGINX, etc.) that the request has passed through
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            # remember the protocol (HTTP or HTTPS) that the client used to connect to NGINX
            proxy_set_header X-Forwarded-Proto $scheme;

            # upgrade the connection to WebSocket(allow long lasting connection) if the client requests it
            # send this upgrade request to the backend (Vite) so that it can handle WebSocket connections
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        # backend request
        location /api/ {
            #  remove `/api/` from URI, forward to NestJS 
			rewrite ^/api/(.*) /$1 break;
			proxy_pass http://backend:3000;
			
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;						# IP
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# IP chain
			proxy_set_header X-Forwarded-Proto $scheme;					    # HTTP or HTTPS
        }


    }
}